#!/bin/sh
echo "Sam Version 0.1"
echo "For multiple word queries use underscore in place of space"
echo "Installing command line utility dafaq and whats"
sudo cp ./dafaq /usr/bin/dafaq
sudo cp ./dafaq /usr/bin/whats
sudo mkdir ~/Sam
sudo cp ./Sam.class ~/Sam/Sam.class
sudo cp ./ServerCode.class ~/Sam/ServerCode.class
sudo cp ./ServerCode\$1.class ~/Sam/ServerCode\$1.class
echo "."
echo "."
echo "."
echo "."
echo "."
echo "."
echo "."
echo "Installed"
echo "You can use both dafaq or whats interchangeably."
echo "Author : Karan Rajpal"
echo "\n"
